version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservices
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - microservices-network

  users-service:
    build: ./users_service
    expose:
      - "5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: microservices
    depends_on:
      - mysql
    networks:
      - microservices-network

  products-service:
    build: ./products_service
    expose:
      - "5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: microservices
    depends_on:
      - mysql
    networks:
      - microservices-network

  orders-service:
    build: ./orders_service
    expose:
      - "5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: microservices
      USERS_SERVICE_URL: http://users-service:5000
      PRODUCTS_SERVICE_URL: http://products-service:5000
    depends_on:
      - mysql
      - users-service
      - products-service
    networks:
      - microservices-network

  storefront-service:
    build: ./storefront_service
    expose:
      - "5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: microservices
      USERS_SERVICE_URL: http://users-service:5000
      PRODUCTS_SERVICE_URL: http://products-service:5000
      ORDERS_SERVICE_URL: http://orders-service:5000
    depends_on:
      - mysql
      - users-service
      - products-service
      - orders-service
    networks:
      - microservices-network

  metrics-service:
    build: ./metrics_service
    expose:
      - "5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: microservices
      MYSQL_PORT: 3306
    depends_on:
      - mysql
    networks:
      - microservices-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - users-service
      - products-service
      - orders-service
      - storefront-service
    networks:
      - microservices-network

volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge
